tilemill:
    image: "selcolumbia/tilemill"
    links:
      - "oync:oync"
      - "db:db"
    ports:
      - "20009:20009" 
      - "20008:20008" 
    command:  ./tilemill/run-tilemill.sh

oync:
    image: "selcolumbia/oync"
    links:
      - "db:db"
    environment:
        OYNC_OSM_API_URL: 'http://159.203.95.2'
    command:  ./bin/run-oync.sh

db:
    image: "mdillon/postgis:9.4"
    environment:
        POSTGRES_DB: 'osm'
